### ISSUE TITLE
Cheatsheet examples?

### ISSUE THREAD

**Issue by sjthespian** [scottcs/dot_hammerspoon#1]
Great work, you've given me some good ideas for my hammerspoon config! (and made me rewrite a bunch of my code :-) )

Any chance you can share some cheatsheet examples? It's just markdown so not that hard to create my own, but seeing what you are already doing could help to give me some direction.

Thanks!

**Comment by scottcs** [comment]
Hey thanks, I'm glad you've found some ideas. :)

I've added some [cheatsheet examples with screenshots](../tree/master/cheatsheets). Hope that helps.
