### ISSUE TITLE
missing '/' cause lost file

### ISSUE THREAD

**Issue by cocobear** [scottcs/dot_hammerspoon#8]
> 2019-08-20 15:00:24:               hazel: Moved /Users/cocobear/Downloads/687474703a2f2f692e696d6775722e636f6d2f6662756b436e782e6a7067.jpeg to /Users/cocobear/Dump
> 2019-08-20 15:00:24:               hazel: Moved /Users/cocobear/Downloads/zprof-0.1.tar.gz to /Users/cocobear/Dump
> 2019-08-20 15:00:24:               hazel: Moved /Users/cocobear/Downloads/门锁 (1).png to /Users/cocobear/Dump

**result:**

> .rw-r--r--@ 160M cocobear 02-28 10:04   /Users/cocobear/Dump

all file had gone, except the last one.
:-(

**Comment by mediapathic** [comment]
Yep, same problem. I now have a "Dump" file which is as big as the last thing that got moved, and lost everything in my Downloads directory older than a week.

You really need to put a warning of this on the main README. "probably useful only to me" is not the same as "YOU WILL DEFINITELY LOSE DATA IF YOU USE DEFAULT CONFIG".

**Comment by scottcs** [comment]
Apologies! I haven't been using hammerspoon in a very long time and wasn't getting alerts about issues. I'm going to push a fix that should make this way less likely to happen.
